apiVersion: apps/v1
kind: Deployment
metadata:
  name: "java-maven-app-deployment"
  namespace: app
  labels:
    app: java-maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-maven-app
  template:
    metadata:
      labels:
        app: java-maven-app
        env: dev
        reason: practice
    spec:
      imagePullSecrets:
        - name: dockhub-creds
      containers:
        - name: java-maven-app
          image: "ranjithasu/java-maven-app-eks:1.0"
          ports:
            - containerPort: 8080
