apiVersion: v1
kind: Service
metadata:
  name: "java-maven-app-service"
  namespace: app
spec:
  selector:
    app: java-maven-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
  type: ClusterIP